### ISSUE TITLE
Some Classes requiring update to API version used

### ISSUE THREAD

**Issue by ghost** [mshanemc/processBuilderBlocks#3]
For Classes PBBLock and PBBUnlock the api version used needs to move to 35 (not tested latest) in order to not receive an error when you attempt to remove a lock or place a lock just as a prior lock action has taken place.

It would benefit most end users to update the api versions used for both these classes here 👍

**Comment by mshanemc** [comment]
closed by [commit 83a680b6965affad6319b499f55cf80169b68b2a](https://github.com/mshanemc/processBuilderBlocks/commit/83a680b6965affad6319b499f55cf80169b68b2a)
